- hosts: bench
  become: yes
  gather_facts: yes
  vars:
    golang_version: 1.13

  roles:
    - user.isucon # #
    - bootstrap # #
    - dev.deploy # #
    - initial-data # #

    - nginx # #
    - mysql
    - golang # #

    # for dev
    - nginx.log-format #
    - external.nginx # #
    - external.shipment #
    - external.payment #

    # for benchmarker
    - external.benchmarker #
    # - external.benchmarker-worker #

  tasks:
    - name: Start default daemons
      become: yes
      become_user: root
      systemd:
        name: "{{ item }}"
        state: restarted
        daemon_reload: yes
        enabled: yes
      loop:
        - nginx.service # #
        - shipment.service #
        - payment.service #
